name: Auto Squash
on:
  schedule:
    - cron: '0 9 * * 1'  # 9AM Monday
  workflow_dispatch:
jobs:
  merge:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: utubo/actions-auto-squash-merge@main
        # source-branch: 'develop'  # default
        # target-branch: 'main'     # default
        target-branch: 'master'

