name: Auto Squash
on:
  schedule:
    - cron: '0 9 * * 1'  # 9AM Monday
  workflow_dispatch:
jobs:
  merge:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4  # ← ここ必須
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - uses: utubo/actions-auto-squash-merge@main
        with:
          target-branch: 'master'
          # source-branch: 'develop'  # default
          # target-branch: 'main'     # default

